DROP SEQUENCE user_seq;
DROP SEQUENCE post_seq;
DROP SEQUENCE comment_seq;

CREATE SEQUENCE user_seq
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE SEQUENCE post_seq
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE SEQUENCE comment_seq
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;
